### ISSUE TITLE
Feature Request: Allow user to set network as well as port. 

### ISSUE THREAD

**Issue by LeifAndersen** [rM-self-serve/webinterface-wifi#2]
I use the tailscale package (https://remarkablewiki.com/tips/tailscale) to be able to connect to my remarkable via wifi when on different networks. It would be great if I could also use the webinterface through the same IP I connect over ssh.

**Comment by rM-self-serve** [comment]
I plan to add a wifi network white/blacklist soon and with that I could consider overriding an ip for a network. 

How is the address you ssh with determined with tailscale? Would a static ip be sufficient?

**Comment by rM-self-serve** [comment]
This is now supported in v2. Specifically the field in the config named 'listen_ip'.
