### ISSUE TITLE
issue tcp code 111

### ISSUE THREAD

**Issue by mohamed25051991** [rM-self-serve/webinterface-wifi#6]
Error: HyperError(
    hyper::Error(
        Connect,
        ConnectError(
            "tcp connect error",
            Os {
                code: 111,
                kind: ConnectionRefused,
                message: "Connection refused",
            },
        ),
    ),
)

**Comment by rM-self-serve** [comment]
Please ensure you have followed the instructions in the readme. If you find difficulty in doing so, please open a support thread in the discord. If an issue persists, you can reopen this and provide information on the issue. More information than the exception would be necessary.

Based on https://github.com/rM-self-serve/webinterface-onboot/issues/5, the USB Web Interface is likely not running. See the Limitations section of the readme for why that may be.
